### PR TITLE
Update package info

### PR DESCRIPTION
**Pull request by CunliangGeng**
Found that the package name is `fdp` but not `fairdatapoint` after a release to pypi.
This PR is to fix the related settings. 
**Users will use `pip install fairdatapoint` to install it, but will still use `import fdp` to import it.**

### CODE REVIEW

**Comment by LourensVeen** [comment]
Hmm. Maybe it would be better if the PyPI name and the package name agree? If `import fairdatapoint` is too long people can always do `import fairdatapoint as fdp`...

**Comment by LourensVeen** [comment]
I know another one: `pip install muscle3` and `import libmuscle`. But that is because MUSCLE 3 consists of various components, of which `libmuscle` is one. So that sort of makes sense.

Why are people going to `import fdp` to begin with? Isn't it an application, not a library?

**Comment by c-martinez** [comment]
I guess we import fdp in our [tests](https://github.com/NLeSC/fairdatapoint/blob/master/tests/test_endpoints.py#L3). If we want to change the package name for consistency, maybe we should be thorough and change it everywhere (folder name, file name, etc, etc). Although I am not too sure if it is necessary...

**Comment by CunliangGeng** [comment]
> Why are people going to import fdp to begin with? Isn't it an application, not a library?
You caught me. Users will never need to import it but we do in tests and executable scripts.
Whether keeping it consistent or not does not affect users at all. I prefer keeping it short for ourselves to use.

**Comment by CunliangGeng** [comment]
Updated the `CHANGELOG.md` based on comments from @arnikz

**Comment by CunliangGeng** [comment]
The PR is ready for review.

**Pull request merged**
